services:
    - type: web
      name: social-network-api
      env: python
      plan: free
      buildCommand: |
          pip install -r requirements/prod.txt
          python manage.py collectstatic --noinput
          python manage.py migrate
      startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
      autoDeploy: true
      envVars:
          - key: DEBUG
            value: '0'
          - key: ENV_FILE
            value: '.env.prod'
